USE [master]
GO
/****** Object:  Database [laughhub1]    Script Date: 18/04/2024 06:24:10 PM ******/
CREATE DATABASE [laughhub1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'laughhub1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.HAINGU\MSSQL\DATA\laughhub1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'laughhub1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.HAINGU\MSSQL\DATA\laughhub1_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [laughhub1] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [laughhub1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [laughhub1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [laughhub1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [laughhub1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [laughhub1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [laughhub1] SET ARITHABORT OFF 
GO
ALTER DATABASE [laughhub1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [laughhub1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [laughhub1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [laughhub1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [laughhub1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [laughhub1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [laughhub1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [laughhub1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [laughhub1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [laughhub1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [laughhub1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [laughhub1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [laughhub1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [laughhub1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [laughhub1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [laughhub1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [laughhub1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [laughhub1] SET RECOVERY FULL 
GO
ALTER DATABASE [laughhub1] SET  MULTI_USER 
GO
ALTER DATABASE [laughhub1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [laughhub1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [laughhub1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [laughhub1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [laughhub1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [laughhub1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'laughhub1', N'ON'
GO
ALTER DATABASE [laughhub1] SET QUERY_STORE = ON
GO
ALTER DATABASE [laughhub1] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [laughhub1]
GO
/****** Object:  Table [dbo].[favorite]    Script Date: 18/04/2024 06:24:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[favorite](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userid] [varchar](255) NOT NULL,
	[videoid] [varchar](255) NOT NULL,
	[likedate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[share]    Script Date: 18/04/2024 06:24:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[share](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userid] [varchar](255) NOT NULL,
	[videoid] [varchar](255) NOT NULL,
	[emails] [text] NULL,
	[sharedate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 18/04/2024 06:24:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [varchar](255) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[fullname] [nvarchar](255) NOT NULL,
	[avatar] [text] NULL,
	[admin] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[video]    Script Date: 18/04/2024 06:24:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[video](
	[id] [varchar](255) NOT NULL,
	[title] [ntext] NOT NULL,
	[poster] [text] NULL,
	[views] [int] NOT NULL,
	[description] [nvarchar](max) NULL,
	[videodate] [datetime] NOT NULL,
	[active] [bit] NOT NULL,
	[category_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[video_category]    Script Date: 18/04/2024 06:24:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[video_category](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[category_name] [nvarchar](255) NOT NULL,
	[description] [nvarchar](max) NULL,
	[created_date] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[favorite]  WITH CHECK ADD  CONSTRAINT [fk_favorite_user] FOREIGN KEY([userid])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[favorite] CHECK CONSTRAINT [fk_favorite_user]
GO
ALTER TABLE [dbo].[favorite]  WITH CHECK ADD  CONSTRAINT [fk_favorite_video] FOREIGN KEY([videoid])
REFERENCES [dbo].[video] ([id])
GO
ALTER TABLE [dbo].[favorite] CHECK CONSTRAINT [fk_favorite_video]
GO
ALTER TABLE [dbo].[share]  WITH CHECK ADD  CONSTRAINT [fk_share_user] FOREIGN KEY([userid])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[share] CHECK CONSTRAINT [fk_share_user]
GO
ALTER TABLE [dbo].[share]  WITH CHECK ADD  CONSTRAINT [fk_share_video] FOREIGN KEY([videoid])
REFERENCES [dbo].[video] ([id])
GO
ALTER TABLE [dbo].[share] CHECK CONSTRAINT [fk_share_video]
GO
ALTER TABLE [dbo].[video]  WITH CHECK ADD  CONSTRAINT [fk_video_category] FOREIGN KEY([category_id])
REFERENCES [dbo].[video_category] ([id])
GO
ALTER TABLE [dbo].[video] CHECK CONSTRAINT [fk_video_category]
GO
USE [master]
GO
ALTER DATABASE [laughhub1] SET  READ_WRITE 
GO
